// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownloadTask(arg1) {
  return window['go']['main']['App']['CancelDownloadTask'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetActiveTasks() {
  return window['go']['main']['App']['GetActiveTasks']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetPlaylistInfo(arg1) {
  return window['go']['main']['App']['GetPlaylistInfo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartDownloadTask(arg1) {
  return window['go']['main']['App']['StartDownloadTask'](arg1);
}
